[package]
name = "blockify"
version = "0.0.3"
description = "A general purpose blockchain support library"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4.23"
ed25519-dalek = "1.0.1"
hex = "0.4.3"
rand = "0.7.3"
record_derive = { version="0.1.0", optional=true }
ring = "0.16.20"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
sha2 = "0.10.6"
thiserror = "1.0.39"
tokio = "1.26.0"
untrusted = "0.9.0"

[features]
default = ["derive"]
derive = ["record_derive"]

[package.metadata]
# set the crate as under development
# this prevents someone else from uploading the same crate name to crates.io
# while you are still working on it
cargo-features = ["publish-lockfile"]
publish-lockfile = true
