[package]
name = "blockify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4.23"
ed25519-dalek = "1.0.1"
rand = "0.7.0"
serde = "1.0.152"
serde_json = "1.0.93"
sha2 = "0.10.6"
