[package]
name = "blockify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4.23"
ed25519-dalek = "1.0.1"
hex = "0.4.3"
rand = "0.7.0"
ring = "0.16.20"
serde = {version="1.0.152", features=["derive"]}
serde_json = "1.0.93"
sha2 = "0.10.6"
tokio = "1.26.0"
untrusted = "0.9.0"
