[package]
name = "record_derive"
version = "0.2.2"
description = "Derive attribute macro for Record trait of blockify crate"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = "2.0.15"
